### ISSUE TITLE
Can I specify the test on mobile only

### ISSUE THREAD

**Issue by macnux** [TGiles/auto-lighthouse#174]
Hi,

Can I specify the test on mobile only?
Also, is it possible to exclude a specific directory or amp pages when crawling?

Regards,

**Comment by TGiles** [comment]
Hi macnux, currently there is no way to tell auto-lighthouse to run mobile only. This would be a small enhancement and so I'll look into writing a PR for that.

As for your second point, there is no way to exclude a specific directory from auto-lighthouse's point of view. The only way to modify the crawling behavior is to set the `--respectRobots` flag to `false`, but that will just ignore `robots.txt` (which is probably _not_ what you want to do). I'm not sure if using the emulated mobile form factor will trigger amp pages or not, that's a good question.

**Comment by TGiles** [comment]
Hi @macnux, if you're still interested in the amp pages question, feel free to open up a new issue!
