### ISSUE TITLE
Passing multiple URLS has no effect

### ISSUE THREAD

**Issue by mhnsn** [TGiles/auto-lighthouse#180]
**Describe the bug**
Passing either a space-delimited or comma-delimited list of URLS causes the app to only run against the first site.

**To Reproduce**
1. `npx auto-lighthouse -u <URL_1> <URL_2>`
2. ???
3. Profit.

**Expected behavior**
Passing multiple websites as an arg should cause each site to be tested.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome.
 - Version Latest

**Additional context**
Running in PowerShell

**Comment by TGiles** [comment]
Hi mhnsn, thanks for filing this! I'll look into reproducing this and see why this is happening. While I reproduce, can you tell me your node version as well? I don't believe it's a node version issue, but it might be useful if I'm unable to reproduce the issue.

**Comment by TGiles** [comment]
@mhnsn don't worry about the repro, apparently I forgot to use the [variadic arguments in commander.js](https://github.com/tj/commander.js/issues/53) this whole time 😅

Thanks again for filing this!
