### ISSUE TITLE
This bug is still present.

### ISSUE THREAD

**Issue by monckey100** [TGiles/auto-lighthouse#257]
This bug is still present.

_Originally posted by @monckey100 in https://github.com/TGiles/auto-lighthouse/issues/245#issuecomment-858084086_

Reproduced by installing auto-lighthouse and then running the command.

**Comment by TGiles** [comment]
Thanks for filing, seems like I simply forgot to release the new version. This should be fixed in 2.0.3, can you confirm? Thanks!
