### ISSUE TITLE
Can I choose JSON output

### ISSUE THREAD

**Issue by tibotiber** [TGiles/auto-lighthouse#54]
Hi, me again ;).

The lighthouse CLI has multiple output formats, [including JSON](https://developers.google.com/web/tools/lighthouse/#json). Does auto-lighthouse has a way to request for other input formats?

Thank you

**Comment by TGiles** [comment]
Currently auto-lighthouse will default to html output, because that's all I needed it to do. I'll start up a PR that will allow different output formats. I'll try to get JSON output first and then the GitHub gists

**Comment by TGiles** [comment]
Realized GitHub gists are out of scope (since there doesn't seem to be a simple way to set that up through the lighthouse node module). Got HTML, JSON, and CSV output however.

**Comment by TGiles** [comment]
Available in version 1.1.0!

**Comment by tibotiber** [comment]
Thanks @TGiles! Super quick turn around :). Tested this morning and it's 👌.
